schema_version: 1

context:
  name: orb-models
  version: 0.6.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/orb_models-${{ version }}.tar.gz
  sha256: 2965c533e1917acc578ffcb3bb46f7ce982ebbf35648a64bb178cb8bbad38a74

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - cached_path >=1.7.1
    - ase >=3.25.0,<4
    - scipy >=1.15.1
    - pytorch >=2.8.0,<3.0.0
    - dm-tree ==0.1.8
    - tqdm >=4.67.1
    - nvalchemi-toolkit-ops >=0.3.0
tests:
  - python:
      imports:
        - orb_models
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Foundation models for computational chemistry.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/orbital-materials/orb-models

extra:
  recipe-maintainers:
    - jan-janssen
